### ISSUE TITLE
Pegin Layout fixes

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-app#399]
## TODOs

- [ ] use "CLAIM NOW" text in toast and operations
- [ ] drop the X to dismiss the toast, use swipe-any-direction to dismiss
- [ ] use dark bg from CLAIM NOW button and "fluo green" for toast background
- [ ] Show CLAIMED in the "BTC Deposit" row after the claim is succesful
- [ ] Use a less rounded button and more contrast for the CLAIM button in operations page ie. 
<img width="153" alt="image" src="https://user-images.githubusercontent.com/3596602/129220972-b8537a99-347c-466b-900c-ffac9d2c8e93.png">
